version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/assessment2
      SPRING_REDIS_HOST: localhost
      SPRING_REDIS_PORT: 6379
    networks:
      - backend

  redis:
    image: "redis:6.2"
    ports:
      - "6379:6379"
    networks:
      - backend

  mongo:
    image: "mongo:4.4"
    ports:
      - "27017:27017"
    networks:
      - backend

networks:
  backend:
    driver: bridge
