server:
  port: 8082

spring:
  application:
    name: petfriends-transporte
  datasource:
    url: jdbc:h2:mem:transportedb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect


  cloud:
    function:
      definition: pedidoDespache;cancelarEntrega
    stream:
      bindings:
        pedidoDespache-in-0:
          destination: pedido-despache-topic
          group: tra-despache-queue
        transporteEntregue-out-0:
          destination: transporte-entregue-topic
        cancelarEntrega-in-0:
          destination: entrega-cancelada-topic
          group: tra-cancelado-queue
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest