server:
  port: 8081

spring:
  application:
    name: petfriends-almoxarifado
  datasource:
    url: jdbc:h2:mem:almoxarifadodb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  cloud:
    stream:
      bindings:
        pedidoEnviado-in-0:
          destination: pedido-enviado-topic
          group: alm-pedido-queue
        almoxarifadoDespache-out-0:
          destination: almoxarifado-despache-topic
        cancelarPedido-out-0:
          destination: pedido-cancelado-topic
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest