name: Java CI Pipeline

on:
  push:
    branches: [ calculadora_web_tp2 ]
    paths:
      - "src/**"

  pull_request:
    paths:
      - "src/**"

  workflow_dispatch:

permissions:
  contents: write

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build Maven
        run: mvn -B clean compile

  test:
    needs: build 
    uses: ./.github/workflows/lint_and_test.yml

  package:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4

      - name: Instalar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Gerar JAR
        run: mvn package


  update-readme:
    runs-on: ubuntu-latest
    needs: [build, test, package]
    if: always()

    steps:
      - name: Simular atualização do README
        run: |
          if [[ "${{ needs.build.result }}" == "success" && \
                "${{ needs.test.result }}" == "success" && \
                "${{ needs.package.result }}" == "success" ]]; then
            echo "README seria atualizado para: Pipeline executou com sucesso."
          else
            echo "README seria atualizado para: Pipeline falhou."
          fi


  comentar-aplicacao:
    runs-on: ubuntu-latest
    needs: [build, test, package]
    if: needs.build.result == 'success' && needs.test.result == 'success' && needs.package.result == 'success'

    steps:
      - name: Simular comentário na aplicação
        run: echo "// Pipeline executada com sucesso seria adicionada na CalculadoraWebApplication"
