name: PB TP5 CRUD Workflow

on:
  push:
    branches:
      - crud_tp5
  pull_request:
    branches:
      - crud_tp5
  workflow_dispatch:
    inputs:
      run_test:
        description: "Run tests"
        required: false
        default: true
        type: boolean
      run_lint:
        description: "Run lint"
        required: false
        default: true
        type: boolean

jobs:
  lint-and-test:
      uses: ./.github/workflows/lint_and_test.yaml
      with:
        run_test: ${{ inputs.run_test || 'true' }}
        run_lint: ${{ inputs.run_lint || 'true' }}
  build:
    runs-on: ubuntu-latest

    env:
      SENHA_JAVA: ${{ secrets.SENHA_JAVA }}
      SALDO_INICIAL: ${{ vars.SALDO_INICIAL }}
      TAXA_TRANSFERENCIA: ${{ vars.TAXA_TRANSFERENCIA }}

    steps:
      - name: Mostrar variaveis
        env:
          VARS_JSON: ${{ toJSON(vars) }}
        run: echo "${VARS_JSON}"

      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Permissão no Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Build do projeto
        uses: gradle/gradle-build-action@v3
        with:
          arguments: build -x test

      - name: Artefato JAR
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: build/libs/*.jar