name: Test Pipeline

on:
  push:
    branches: [ calculadora_web ]
  pull_request:
    branches: [ calculadora_web ]

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Mensagem
        run: echo "Pipeline iniciado com sucesso"
