  
name: Linting e Teste

on:
  workflow_call:
    inputs:
      run_test:
        required: true
        type: boolean
      run_lint:
        required: true
        type: boolean

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    if: ${{ inputs.run_lint }}
    steps:
      - uses: actions/checkout@v6
      - uses: dbelyaev/action-checkstyle@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  test:
    runs-on: ubuntu-latest
    if: ${{ inputs.run_test }}
    steps:
      - uses: actions/checkout@v4

      - name: Instalar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Executar testes
        run: mvn test